# Generated by Django 4.2.10 on 2024-03-01 22:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('falls', '0004_alter_emergencycontact_phone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emergencycontact',
            name='phone',
            field=models.CharField(max_length=15),
        ),
    ]
