# Generated by Django 4.2.10 on 2024-03-02 05:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('falls', '0006_alter_emergencycontact_phone_customuser_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Fall',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', models.TimeField()),
                ('date', models.DateField()),
                ('heartbeat', models.IntegerField()),
            ],
        ),
    ]
